In [1]:
import numpy as np 

##create array using numpy
## create a 1D array

arr1=np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr1)
print(type(arr1))
print(arr1.shape)


[[1 2 3 4 5]
 [2 3 4 5 6]]
<class 'numpy.ndarray'>
(2, 5)


In [2]:
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5)   ##1 row 5 columns


array([[1, 2, 3, 4, 5]])

In [3]:
arr2 = np.array([[1,2,3,4,5]])
arr2.shape


(1, 5)

In [4]:
np.arange(0,10,2).reshape(5,1)  ##start, stop, step


array([[0],
       [2],
       [4],
       [6],
       [8]])

In [5]:
np.ones((3,4))


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [6]:
## identity matrix
np.eye(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [7]:
## attributes of numpy array
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

print("Array is: ", arr)
print("Shape of array is: ", arr.shape) 
print("Data type of array is: ", arr.dtype)
print("Size of array is: ", arr.size)
print("Number of dimensions of array is: ", arr.ndim)
print("Number of bytes of each element of array is: ", arr.itemsize)
print("Total number of bytes of array is: ", arr.nbytes)


Array is:  [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Shape of array is:  (3, 4)
Data type of array is:  int32
Size of array is:  12
Number of dimensions of array is:  2
Number of bytes of each element of array is:  4
Total number of bytes of array is:  48


In [8]:
### Numpy vectorized operations
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])

### element wise addition
print(arr1 + arr2)

### element wise subtraction
print(arr1 - arr2)

### element wise multiplication
print(arr1 * arr2)



[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]


In [9]:
## universal functions
arr = np.array([1,2,3,4,5])

print("square root of array is: ", np.sqrt(arr))
print("exponential of array is: ", np.exp(arr))
print("sine of array is: ", np.sin(arr))
print("cosine of array is: ", np.cos(arr))
print("log of array is: ", np.log(arr))
print("sum of array is: ", np.sum(arr))
print("mean of array is: ", np.mean(arr))
print("standard deviation of array is: ", np.std(arr))
print("minimum of array is: ", np.min(arr))
print("maximum of array is: ", np.max(arr))
print("index of minimum element of array is: ", np.argmin(arr))
print("index of maximum element of array is: ", np.argmax(arr))
print("index of sorted array is: ", np.argsort(arr))
print("unique elements of array is: ", np.unique(arr))
print("count of unique elements of array is: ", np.unique(arr, return_counts=True))


square root of array is:  [1.         1.41421356 1.73205081 2.         2.23606798]
exponential of array is:  [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
sine of array is:  [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
cosine of array is:  [ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]
log of array is:  [0.         0.69314718 1.09861229 1.38629436 1.60943791]
sum of array is:  15
mean of array is:  3.0
standard deviation of array is:  1.4142135623730951
minimum of array is:  1
maximum of array is:  5
index of minimum element of array is:  0
index of maximum element of array is:  4
index of sorted array is:  [0 1 2 3 4]
unique elements of array is:  [1 2 3 4 5]
count of unique elements of array is:  (array([1, 2, 3, 4, 5]), array([1, 1, 1, 1, 1], dtype=int64))


In [10]:
## array slicing and indexing 
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print("Array is: \n", arr)
print("Element at 0th row and 0th column is: ", arr[0,0])
print("Element at 1st row and 1st column is: ", arr[1,1])


Array is: 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Element at 0th row and 0th column is:  1
Element at 1st row and 1st column is:  7


In [11]:
print(arr[1:,1:3])


[[7 8]]


In [12]:
print(arr[0][0])
print(arr[0:2,2:])


1
[[ 3  4  5]
 [ 8  9 10]]


In [13]:
## modify array elements
arr[0,0] = 100
print(arr)


[[100   2   3   4   5]
 [  6   7   8   9  10]]


In [14]:
arr[1:] = 100
print(arr)


[[100   2   3   4   5]
 [100 100 100 100 100]]


In [15]:
data = np.array([1,2,3,4,5,6,7,8,9,10])

#Mean
mean = np.mean(data)
print("Mean: ", mean)

#Median
median = np.median(data)
print("Median: ", median)

#Standard Deviation
std_dev = np.std(data)
print("Standard Deviation: ", std_dev)

#Variance
variance = np.var(data)
print("Variance: ", variance)


Mean:  5.5
Median:  5.5
Standard Deviation:  2.8722813232690143
Variance:  8.25


In [16]:
### statistical concepts -- normalizations

data = np.array([1,2,3,4,5,6,7,8,9,10])

## calculate mean
mean = np.mean(data)
std_dev = np.std(data)

## normalize data
normalized_data = (data - mean)/std_dev
print(normalized_data)


[-1.5666989  -1.21854359 -0.87038828 -0.52223297 -0.17407766  0.17407766
  0.52223297  0.87038828  1.21854359  1.5666989 ]


In [17]:
### logical operations
data = np.array([1,2,3,4,5,6,7,8,9,10])

data[(data > 5) & (data <= 8)]


array([6, 7, 8])